export function createInitialAppState() {
    const savedVolume = parseFloat(window.localStorage?.getItem('toolbar_tts_volume') || '0.9');

    return {
        isRunning: false,
        isStarting: false,
        runToggleInProgress: false,
        currentSource: 'system',
        translationMode: 'local',
        transcriptUI: null,
        localPipelineChannel: null,
        localPipelineReady: false,
        localPipelineClosed: false,
        platformInfo: { os: 'unknown', arch: 'unknown' },
        isLocalSetupRunning: false,
        localSetupReady: false,
        recordingStartTime: null,
        deepgramTranslationQueue: Promise.resolve(),
        deepgramRecentTranslatedTexts: [],
        lastDeepgramTranslatedAt: 0,
        deepgramLastTranslatedByGroup: new Map(),
        deepgramLatestRevisionByGroup: new Map(),
        deepgramPreparedTranslationKey: null,
        deepgramPendingGroup: null,
        deepgramFlushTimer: null,
        deepgramFlushDelayMs: 450,
        deepgramPreviewDelayMs: 180,
        deepgramGroupCounter: 0,
        deepgramSessionId: 0,
        deepgramEventStats: null,
        deepgramDebugSessionId: null,
        localTranslationQueue: Promise.resolve(),
        localPreparedTranslationKey: null,
        localLatestRevisionByGroup: new Map(),
        localLastTranslatedByGroup: new Map(),
        localSentenceStateByUtterance: new Map(),
        localRecentCommittedGroups: [],
        localCarryOver: null,
        localCarryOverTimeout: null,
        localSessionId: 0,
        localPipelineConfig: null,
        localActualModel: null,
        ttsEnabled: false,
        isPinned: false,
        themeMode: 'dark',
        currentAccentPreset: 'violet-neon',
        currentLocale: 'vi',
        systemThemeMedia: window.matchMedia?.('(prefers-color-scheme: dark)') || null,
        activePanelTab: 'panel-stt',
        settingsAutosaveTimer: null,
        settingsAutosavePromise: Promise.resolve(),
        toolbarTtsVolume: Number.isFinite(savedVolume)
            ? Math.min(1, Math.max(0, savedVolume))
            : 0.9,
    };
}